# DataSource Config
spring:
  application:
    name: campus-partner-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dyz200472
    url: jdbc:mysql://localhost:3306/zhezi?useSSL=false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    timeout: 86400
    store-type: redis
  redis:
    port: 6379
    host: localhost
    database: 0
  main:
    allow-circular-references: true
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8080
  servlet:
    context-path: /api
  reactive:
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


